using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using Perch.Statusline;
using Xunit;

namespace Perch.Tests;

/// <summary>The standalone-script generator: it bakes the template in, produces a <c>node "…"</c>
/// command, and — crucially — renders byte-for-byte the same as the in-process C# engine. The parity
/// cases run the generated script under <c>node</c> and diff its stdout against
/// <see cref="StatuslineTemplate"/>; they self-skip when Node isn't on PATH.</summary>
public sealed class StatuslineScriptTests
{
    [Fact]
    public void Generate_bakes_in_template_and_name()
    {
        var script = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "My Cool Line",
            Template = "{{model.display_name}}",
        });
        Assert.Contains("\"{{model.display_name}}\"", script);   // JSON-encoded template literal
        Assert.Contains("My Cool Line", script);                  // name echoed into the header comment
        Assert.DoesNotContain("@@TEMPLATE@@", script);
        Assert.DoesNotContain("@@NAME@@", script);
    }

    [Fact]
    public void CommandFor_wraps_the_path_for_node() =>
        Assert.Equal("node \"C:\\a b\\perch-statusline.mjs\"",
            StatuslineScript.CommandFor("C:\\a b\\perch-statusline.mjs"));

    [Fact]
    public void Generate_gates_git_counts_on_template_use()
    {
        var withCounts = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "g", Template = "{{git.branch}} (+{{git.staged}},-{{git.unstaged}})",
        });
        Assert.Contains("const NEED_GIT_COUNTS = true;", withCounts);
        Assert.Contains("execFileSync", withCounts);   // the git subprocess is present

        var withoutCounts = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "b", Template = "{{model.display_name}} {{git.branch}}",   // branch only, no counts
        });
        Assert.Contains("const NEED_GIT_COUNTS = false;", withoutCounts);
    }

    [Fact]
    public void Generate_gates_account_read_on_template_use()
    {
        var withAccount = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "a", Template = "{{account.org|default:{{account.email}}}}",
        });
        Assert.Contains("const NEED_ACCOUNT = true;", withAccount);
        Assert.Contains("oauthAccount", withAccount);   // the .claude.json read is present

        var withoutAccount = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "b", Template = "{{model.display_name}} {{git.branch}}",
        });
        Assert.Contains("const NEED_ACCOUNT = false;", withoutAccount);
    }

    [Fact]
    public void Generate_gates_perch_read_on_template_use()
    {
        var withCtxcolor = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "a", Template = "{{context_window.used_percentage|bar:8|ctxcolor}}",   // filter, no perch.* path
        });
        Assert.Contains("const NEED_PERCH = true;", withCtxcolor);

        var withPerchToken = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "b", Template = "{{#perch.guardrail.mismatch}}!{{/perch.guardrail.mismatch}}",
        });
        Assert.Contains("const NEED_PERCH = true;", withPerchToken);
        Assert.Contains("AccountRules", withPerchToken);   // the settings.json read (guardrail) is present

        var without = StatuslineScript.Generate(new StatuslineProfile
        {
            Name = "c", Template = "{{model.display_name}} {{git.branch}}",
        });
        Assert.Contains("const NEED_PERCH = false;", without);
    }

    [Fact]
    public void Generate_bakes_the_dev_marker_only_when_asked()
    {
        var p = new StatuslineProfile { Name = "d", Template = "{{model.display_name}}" };
        var dev = StatuslineScript.Generate(p, devMarker: true);
        Assert.Contains("const DEV = true;", dev);
        Assert.Contains("[generated by a Perch DEV instance]", dev);   // the header note

        var rel = StatuslineScript.Generate(p, devMarker: false);
        Assert.Contains("const DEV = false;", rel);
        Assert.DoesNotContain("[generated by a Perch DEV instance]", rel);
    }

    [Fact]
    public void Dev_marker_is_prepended_at_runtime_when_dev()
    {
        var node = FindNode();
        if (node is null) return;

        var dir = Path.Combine(Path.GetTempPath(), "perch-sl-node-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var profile = new StatuslineProfile { Name = "t", Template = "{{model.display_name}}" };
            var scriptPath = Path.Combine(dir, "line.mjs");
            var payload = """{"model":{"display_name":"Opus"}}""";

            File.WriteAllText(scriptPath, StatuslineScript.Generate(profile, devMarker: true));
            var devOut = RunNode(node, scriptPath, payload);
            Assert.Contains(" dev ", devOut);          // the marker text
            Assert.Contains("48;2;227;168;78", devOut); // amber background SGR
            Assert.EndsWith("Opus", devOut);            // the line itself still renders after the marker

            File.WriteAllText(scriptPath, StatuslineScript.Generate(profile, devMarker: false));
            Assert.Equal("Opus", RunNode(node, scriptPath, payload));   // release: no marker
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { }
        }
    }

    [Fact]
    public void Generate_requires_a_template() =>
        Assert.Throws<InvalidOperationException>(() =>
            StatuslineScript.Generate(new StatuslineProfile { Name = "x", Template = null }));

    // ── parity: generated Node script == C# engine ──────────────────────────────────────
    public static TheoryData<string, string> ParityCases() => new()
    {
        // filters + colour
        { "{{model.display_name}} {{context_window.used_percentage|bar:8|color:teal}} {{context_window.used_percentage|pct}} ${{cost.total_cost_usd|money}}",
          """{"model":{"display_name":"Opus"},"context_window":{"used_percentage":34},"cost":{"total_cost_usd":0.4213}}""" },
        // half-up rounding parity (2.5 -> 3, 0.5 -> 1, 23.5 -> 24)
        { "{{a|round}} {{b|round}} {{c|pct}}", """{"a":2.5,"b":0.5,"c":23.5}""" },
        // round:N decimal places — trailing zeros trimmed; both engines format from integer/string ops
        { "{{a|round:2}} {{b|round:1}} {{c|round:2}} {{d|round}} {{e|round:3}}",
          """{"a":0.4213,"b":2.5,"c":3.1,"d":23.5,"e":1}""" },
        // conditionals: comparison, inverted, string equality
        { "{{#if x > 80}}HI{{/if}}[{{^y}}NOy{{/y}}]{{#if s == 'pending'}}P{{/if}}",
          """{"x":87,"y":false,"s":"pending"}""" },
        // missing / default / trunc / upper / k
        { "{{nope|default:n a}}|{{path|trunc:6}}|{{lvl|upper}}|{{tok|k}}",
          """{"path":"/home/x/project","lvl":"high","tok":68000}""" },
        // the built-in default template, with git supplied in the payload (no cwd -> no injection)
        { StatuslineDefaults.All[0].Template!,
          """{"model":{"display_name":"Opus"},"git":{"branch":"main"},"context_window":{"used_percentage":34},"cost":{"total_cost_usd":0.4213},"pr":{"number":30,"review_state":"pending"}}""" },
        // two-line template
        { StatuslineDefaults.All[2].Template!,
          """{"model":{"display_name":"Opus"},"effort":{"level":"high"},"git":{"branch":"main"},"context_window":{"used_percentage":34},"prompt_cache":{"warm":true,"ttl":"1h"},"rate_limits":{"five_hour":{"used_percentage":23.5}}}""" },
        // formatters added for the rate-aware example
        { "{{a|human}} {{b|human}} {{c|human}}", """{"a":999,"b":68000,"c":2500000}""" },
        { "{{a|dur}} {{b|dur}} {{c|dur}}", """{"a":45000,"b":300000,"c":4500000}""" },
        // pace with a reset far in the future → expected clamps to 0 (< 15 → green), independent of each
        // process's wall clock, so the C# engine and the Node script still agree byte-for-byte
        { "{{u|bar:10|pace:r:18000}} {{u|round|pace:r:18000}}%", """{"u":40,"r":4102444800}""" },
        // soft breaks ("\" + newline) must be dropped identically by both engines
        { "ctx {{context_window.used_percentage|pct}}\\\n  ${{cost.total_cost_usd|money}}",
          """{"context_window":{"used_percentage":34},"cost":{"total_cost_usd":0.4213}}""" },
        // {{sep}} collapse: the empty middle conditional must drop one divider, both engines alike
        { "{{a}}{{sep}}{{#if m}}{{m}}{{/if}}{{sep}}{{b}}", """{"a":"AAA","b":"BBB"}""" },
        { "{{a}}{{sep:·}}{{#if m}}{{m}}{{/if}}{{sep:·}}{{b}}", """{"a":"AAA","m":"MID","b":"BBB"}""" },
        // custom hex colours (named + hex, 3- and 6-digit) render the same truecolor escapes
        { "{{a|color:#ff8800}} {{b|color:1a2b3c}} {{c|color:#f80}} {{d|color:teal}}",
          """{"a":"A","b":"B","c":"C","d":"D"}""" },
        // account extras: supplied in the payload so the Node injector's "skip if present" leaves it alone
        // and both engines read the same object — the host's real login can't perturb parity.
        { "{{#account.signed_in}}{{account.org|default:personal}} <{{account.email}}>{{/account.signed_in}}",
          """{"account":{"email":"you@example.com","org":"Example Org","org_uuid":"u","signed_in":true,"personal":false}}""" },
        // ctxcolor: perch.context supplied in the payload so injectPerch's "skip if present" leaves it alone —
        // both engines colour the same numeric value against the same bands (72 → orange band → amber).
        { "{{context_window.used_percentage|bar:8|ctxcolor}} {{context_window.used_percentage|pct|ctxcolor}}",
          """{"context_window":{"used_percentage":72},"perch":{"context":{"yellow":50,"orange":65,"red":80}}}""" },
        // guardrail: a supplied perch.guardrail means neither engine reads real config — the wrong-account
        // warning renders identically (and stays silent when mismatch is false, via the inverted section).
        { "{{#perch.guardrail.mismatch}}⚠ {{perch.guardrail.expected|color:red}} ≠ {{perch.guardrail.on|color:red}}{{/perch.guardrail.mismatch}}",
          """{"perch":{"guardrail":{"mismatch":true,"expected":"Acme","on":"Contoso"}}}""" },
        // if / elseif / else chain — the middle branch wins (60 is >50 but not >80)
        { "{{#if x > 80}}HI{{elseif x > 50}}MID{{else}}LO{{/if}}", """{"x":60}""" },
        // else on a truthy section (no PR → the else branch), and on an inverted section
        { "{{#pr.number}}PR {{pr.number}}{{else}}no pr{{/pr.number}} | {{^err}}ok{{else}}ERR{{/err}}",
          """{"err":false}""" },
        // background region: a coloured token inside a red-bg region, plus plain text carrying the bg;
        // an inner hex-bg region overrides the outer one
        { "{{#bg:red}} {{model.display_name|color:teal}} {{#bg:#112233}}IN{{/bg}} out {{/bg}}",
          """{"model":{"display_name":"Opus"}}""" },
        // blank output lines dropped: a false leading conditional line + a whitespace-only middle line both
        // vanish, so both engines emit only the two content rows
        { "{{#if warn}}⚠{{/if}}\n {{gone}} \n{{model.display_name}}\nctx {{context_window.used_percentage|pct}}",
          """{"model":{"display_name":"Opus"},"context_window":{"used_percentage":34}}""" },
    };

    [Theory]
    [MemberData(nameof(ParityCases))]
    public void Generated_script_matches_the_csharp_engine(string template, string payloadJson)
    {
        var node = FindNode();
        if (node is null) return;   // Node not installed on this host — skip (Claude Code guarantees it in the field)

        var expected = StatuslineTemplate.RenderToString(template, TemplateData.Parse(payloadJson), color: true);

        var dir = Path.Combine(Path.GetTempPath(), "perch-sl-node-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var scriptPath = Path.Combine(dir, "line.mjs");
            // devMarker:false — the parity target is the pure engine, which never adds the dev marker (and the
            // test build is itself a dev build, so the default would).
            File.WriteAllText(scriptPath, StatuslineScript.Generate(new StatuslineProfile { Name = "t", Template = template }, devMarker: false));
            var actual = RunNode(node, scriptPath, payloadJson);
            Assert.Equal(expected, actual);
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { }
        }
    }

    // The one path parity can't cover: a payload with NO perch block, so the generated script actually runs
    // injectPerch — reading (or failing to find) Perch's real settings.json and falling back to defaults. It
    // must never crash and must still render. The bar TEXT is threshold-independent, so this stays
    // deterministic no matter what (if anything) is on the test host.
    [Fact]
    public void Generated_script_survives_a_payload_with_no_perch_block()
    {
        var node = FindNode();
        if (node is null) return;

        var dir = Path.Combine(Path.GetTempPath(), "perch-sl-node-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var scriptPath = Path.Combine(dir, "line.mjs");
            File.WriteAllText(scriptPath, StatuslineScript.Generate(new StatuslineProfile
            {
                Name = "t", Template = "{{u|bar:8|ctxcolor}}{{#perch.guardrail.mismatch}} ⚠{{/perch.guardrail.mismatch}}",
            }, devMarker: false));
            var actual = RunNode(node, scriptPath, """{"u":60,"cwd":"/tmp/nowhere"}""");
            Assert.Contains("█", actual);   // 60% → filled cells present; ctxcolor defaulted, didn't throw
            Assert.Contains("░", actual);   // and empty cells — the whole 8-cell bar rendered
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { }
        }
    }

    private static string? FindNode()
    {
        try
        {
            using var p = Process.Start(new ProcessStartInfo("node", "--version")
            {
                RedirectStandardOutput = true, RedirectStandardError = true, UseShellExecute = false,
            });
            if (p is null) return null;
            p.WaitForExit(5000);
            return p.ExitCode == 0 ? "node" : null;
        }
        catch
        {
            return null;
        }
    }

    private static string RunNode(string node, string scriptPath, string stdin)
    {
        using var p = new Process
        {
            StartInfo = new ProcessStartInfo(node, $"\"{scriptPath}\"")
            {
                RedirectStandardInput = true,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                StandardInputEncoding = new UTF8Encoding(false),
                StandardOutputEncoding = new UTF8Encoding(false),
            },
        };
        p.Start();
        p.StandardInput.Write(stdin);
        p.StandardInput.Close();
        var outp = p.StandardOutput.ReadToEnd();
        p.WaitForExit(10000);
        return outp;
    }
}
