using System.Reflection;

namespace Perch.Data;

/// <summary>One searchable emoji: the glyph itself, its human name, and the space-separated keyword tokens the
/// search matches against (name words + GitHub shortcode aliases + tags + category, lowercased and de-duplicated).</summary>
public readonly record struct EmojiEntry(string Emoji, string Name, string Keywords);

/// <summary>
/// The full, searchable emoji set behind Perch's own picker — a replacement for leaning on the OS emoji dialog.
/// Loaded once from an embedded dataset (<c>Perch.emoji-data.tsv</c>, generated by <c>tools/gen-emoji.py</c> from
/// GitHub's gemoji list); every glyph in it renders on both a current Windows (Segoe UI Emoji) and macOS (Apple
/// Color Emoji), so a search result is safe to show cross-platform.
///
/// <para><see cref="Search"/> ranks by match quality: an exact name/alias beats a prefix beats a substring, and a
/// multi-word query is AND-ed across its words (every word must hit some keyword), so "smiling cat" narrows rather
/// than widens. Ties fall back to the dataset's natural (roughly Unicode) order, so results are stable.</para>
/// </summary>
public static class EmojiCatalog
{
    // Held with the entry so scoring never re-splits/re-lowercases per query.
    private readonly record struct Indexed(EmojiEntry Entry, string NameLower, string[] Tokens);

    private static readonly char[] Space = [' '];
    private static readonly Lazy<IReadOnlyList<Indexed>> _index = new(Load);

    /// <summary>Every emoji in the dataset, in the source's natural order.</summary>
    public static IReadOnlyList<EmojiEntry> All
    {
        get
        {
            var idx = _index.Value;
            var list = new List<EmojiEntry>(idx.Count);
            foreach (var i in idx) list.Add(i.Entry);
            return list;
        }
    }

    /// <summary>Emoji whose name/keywords match <paramref name="query"/>, best first, at most <paramref name="limit"/>.
    /// A blank query yields nothing (the picker shows recents instead). Matching is case-insensitive; a multi-word
    /// query requires every word to match some keyword.</summary>
    public static IReadOnlyList<EmojiEntry> Search(string? query, int limit = 60)
    {
        if (string.IsNullOrWhiteSpace(query)) return [];
        var q = query.Trim().ToLowerInvariant();
        var qtokens = q.Split(Space, StringSplitOptions.RemoveEmptyEntries);
        if (qtokens.Length == 0) return [];

        var idx = _index.Value;
        var hits = new List<(int Score, int Order)>();
        for (int i = 0; i < idx.Count; i++)
        {
            int s = Score(idx[i], q, qtokens);
            if (s > 0) hits.Add((s, i));
        }

        hits.Sort((a, b) =>
        {
            int byScore = b.Score.CompareTo(a.Score);
            return byScore != 0 ? byScore : a.Order.CompareTo(b.Order);
        });

        int take = limit >= 0 ? Math.Min(limit, hits.Count) : hits.Count;
        var result = new List<EmojiEntry>(take);
        for (int i = 0; i < take; i++) result.Add(idx[hits[i].Order].Entry);
        return result;
    }

    // Scores one entry against the query. Whole-query name hits earn a large bonus; then every query word must
    // match some keyword token (exact > prefix > substring) or the entry is rejected — AND semantics.
    private static int Score(in Indexed e, string q, string[] qtokens)
    {
        int score = 0;
        if (e.NameLower == q) score += 1000;
        else if (e.NameLower.StartsWith(q, StringComparison.Ordinal)) score += 400;

        foreach (var qt in qtokens)
        {
            int best = 0;
            foreach (var kt in e.Tokens)
            {
                if (kt.Length < qt.Length) continue;
                if (kt == qt) { best = 100; break; }                       // can't beat exact — stop early
                if (kt.StartsWith(qt, StringComparison.Ordinal)) best = Math.Max(best, 60);
                else if (kt.Contains(qt, StringComparison.Ordinal)) best = Math.Max(best, 25);
            }
            if (best == 0) return 0;                                       // this word matched nothing → not a hit
            score += best;
        }
        return score;
    }

    private static IReadOnlyList<Indexed> Load()
    {
        var list = new List<Indexed>(2048);
        using var stream = typeof(EmojiCatalog).Assembly.GetManifestResourceStream("Perch.emoji-data.tsv");
        if (stream is null) return list;                                   // never expected; fail soft to "no emoji"
        using var reader = new StreamReader(stream);
        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            if (line.Length == 0) continue;
            var parts = line.Split('\t');
            if (parts.Length < 3) continue;                               // emoji, name, keywords[, version]
            var entry = new EmojiEntry(parts[0], parts[1], parts[2]);
            var tokens = parts[2].Split(Space, StringSplitOptions.RemoveEmptyEntries);
            list.Add(new Indexed(entry, parts[1].ToLowerInvariant(), tokens));
        }
        return list;
    }
}
